twilio:
  accountId: ACcbedb2b43159d11693306f590cb2f3ba
  accountToken: be66f5bbd8ead654e193b97fbf317786
  localDomain:  signal.taolu.biz
  numbers:
    - "+17243993889" # Change this to your number from Twilio

backupService:
  userAuthenticationTokenSharedSecret: 112233445566  # Generate it with `head -c 16 /dev/urandom | hexdump -ve '1/1 "%.2x"'`

storageService:
  userAuthenticationTokenSharedSecret: 778899AABBCC  # Generate it with `head -c 16 /dev/urandom | hexdump -ve '1/1 "%.2x"'`

push:
  queueSize: 200

turn: # Coturn server configuration
  secret: secret # You will need the same config with the secret in turnserver.conf
  uris:
    - stun:127.0.0.1:3478 # If you change the port in turnserver.conf, change this too
    - stun:127.0.0.1:5349 # If you change the port in turnserver.conf, change this too
    - turn:127.0.0.1:5349?transport=udp # If you change the port in turnserver.conf, change this too
    - turn:127.0.0.1:3478?transport=udp # If you change the port in turnserver.conf, change this too

cache: # redis server for cache cluster
  url: redis://172.16.4.196:6379/cache # change to your redis server
  replicaUrls:
    - redis://172.16.4.196:6379/cacheReplica # change to your redis server

directory:
  redis: # Redis server configuration for directory cluster
    url: redis://172.16.4.196:6379/directory
    replicaUrls:
      - redis://172.16.4.196:6379/directoryReplica
  client: # Configuration for interfacing with Contact Discovery Service cluster
    userAuthenticationTokenSharedSecret: 33445566  # Generate it with `head -c 16 /dev/urandom | hexdump -ve '1/1 "%.2x"'`
    userAuthenticationTokenUserIdSecret: 22117788  # Generate it with `head -c 16 /dev/urandom | hexdump -ve '1/1 "%.2x"'`
  sqs:
    accessKey:    AKIAQ565H442HJM00000 # Change this to your AWS IAM Access Key
    accessSecret: cvjr4YVENZW/samH3G33ntliGVKM3oVYJh300000 # Change this to your AWS IAM Secret
    queueUrl:     https://sqs.eu-west-3.amazonaws.com/044351627060/signal.fifo # Change this to your AWS SQS (FIFO) URL
  server: # You can change the certificate with your own certificate
    replicationUrl: http://127.0.0.1:9090 # CDS replication endpoint base url
    replicationPassword: mypassword # CDS replication endpoint password
    replicationCaCertificate: |
      -----BEGIN CERTIFICATE-----
      MIIF7zCCA9egAwIBAgIUUme0O2hOX+OWLwfKyIzgMFl4sjcwDQYJKoZIhvc00000
      BQAwgYYxCzAJBgNVBAYTAklEMRQwEgYDVQQIDAtES0kgSmFrYXJ0YTEQMA4GA1UE
      BwwHSmFrYXJ0YTEPMA0GA1UECgwGVGVsa29tMQwwCgYDVQQLDANEZXYxEDAOBgNV
      BAMMB2NoYXRhcHAxHjAcBgkqhkiG9w0BCQEWD2RldkBleGFtcGxlLmNvbTAeFw0y
      MDAxMTAwODEzMzFaFw0yMTAxMDkwODEzMzFaMIGGMQswCQYDVQQGEwJJRDEUMBIG
      A1UECAwLREtJIEpha2FydGExEDAOBgNVBAcMB0pha2FydGExDzANBgNVBAoMBlRl
      bGtvbTEMMAoGA1UECwwDRGV2MRAwDgYDVQQDDAdjaGF0YXBwMR4wHAYJKoZIhvcN
      AQkBFg9kZXZAZXhhbXBsZS5jb20wggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIK
      AoICAQCzGVGK0BM47gmPKE5DlNPuXIA/Jx+DdBMUhyt4AxxrtPBjbruVO05OMjcT
      qAXO+DatSQZT/K2/0oQACevrKIkBhXJwe4iUjWNb7nymntG8NKoQbByksYMTLXlj
      OrkPB9fOiGIFlNCZkFDdTkvMrjacjJvXtOMJMkc2UwUtNQ3ss5XLzVFx5J21Q3oo
      Ee1qnGJTUnmvOdCJHJzr7z7VdS6xeN6SOfmRPUi8LdKSbRG8KUcMPFMfMH1yvj6d
      eoTMPEuYq0Pm8j6yR7j+gHaRprlPAAPy9T7N5mN9Pdc7wDLo1qOr7TJ0PgLD641L
      o7uvS0u21tX2g/cR7cBzaEMV0XOJqh3LjHDlbJ1yUXXFSOLcLnXgmmrHL2HqTslF
      DDIh0ns8xG6iaI2CG7xHTJBfFhO0tA1yyUbivSQBRmJNozAPFTfOHtWNCesMJPFC
      x4FPp1iRQwBhAsJ3D80Fd+RNJH7WxP/ffEHPz2AbVqSSPdFjkI5xSqQLR5/k3bMa
      xGu7w0qQ7ifFYOEtETe+Xo1cUYbnheFPUoExxoRcWWl/42uTGsZazTlUo+LWH0yb
      xEB+MWmPREYqeCaoRIXV5UTsDlXjuQpRnIDl1xgdUkFTN6Trfn0eAUuRNM0bbQNL
      hDwCCLU4c2oY1mGgcXklxzOZIk5KQMFSMlOkVGhM6R2MmL1UWQIDAQABo1MwUTAd
      BgNVHQ4EFgQUBe0rUnGIOfQFvFcSzKB6HQhbCVYwHwYDVR0jBBgwFoAUBe0rUnGI
      OfQFvFcSzKB6HQhbCVYwDwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOC
      AgEAmnb/xuo8AcqzL+cVnu+SSxHHJPPhMM7Bnm8ChFnw/CqeTRbxwa5Po7tj47CF
      ZH9NPpi3UEYGhAeyTcIPpa7mcgaIDoOrYA7Ku6BT2/KhlQu6vVg5xw3QBrnfplm+
      9VOnfKKoH7nD2lrW7rVZ/EZGzeChtI0AzCAlcnBQCnXziY5++LkWCzPmofHq+moP
      OAHyLMb3pUyPdCgTETLrrgNixrlb5s/rqTrwNe3XUo1YrPMTYzCN5mrCqQtOsvFp
      2L+y8RlfQ+AFJeQDCC6eUFYfK3Ls6qz7agm19EmyXO642M5eOdT4tobgt24YsnGx
      TupofOEbBU9F31LELSwe3bAu5N8RZvhay5C5u9ZrrUNlp1pr1Ljy0r51SmckmyY7
      4g8IT28E3cZhyFUsqwihxlwf9oHhxAzxOTVWiSobibc8r0q3hp3PutQFyPLRrfMf
      hDPTpUPm8v1rFRxNWXpe3w92y/iiJ53S4CWVmBIW9iKGqOyj7l2VEqe7KGKVO3Ma
      Z5b5jQMf6d2N1Qk2tt8YnL6EbT0mOJedhAfnkJl71UZzK7Lz1kLT+1MnlF+gazol
      vJiET6YNSW7sU/GNafapLfIqXU2wCfOFcrLEsW+DOEM2MLcY48ypPDcnwsl6OG+K
      qXeFHFld6v6s6pIGmc50pflU4qSJHAASDsUxw08xKxXnTEg=
      -----END CERTIFICATE-----
messageCache: # redis server for message store cache
  redis:
    url: redis://172.16.4.196:6379/messageCache # change to your redis server
    replicaUrls:
      - redis://172.16.4.196:6379/messageCacheReplica # change to your redis server

awsAttachments: # aws s3 configuration
  accessKey: AKIAQ565H442DES00000 # Change this to your AWS IAM Access Key
  accessSecret: YmpZCxz2lzgemvmLTa2uC38IG2ADBFztm5l00000 # Change this to your AWS IAM Secret
  bucket: signal-01-attachments # Change this to your bucket's name
  region: eu-west-3 # Change this to your bucket's region

cdn: # aws cdn configuration
  accessKey: AKIAQ565H242DES00000 # Change this to your AWS IAM Access Key
  accessSecret: YmpZCxf2lzgembmLTa2uC38IG2ADBFztm5l00000 # Change this to your AWS IAM Secret
  bucket: signal-01-attachments # Change this to your bucket's name
  region: eu-west-3 # Change this to your bucket's region

# openssl genrsa -out private_key_rsa_4096_pkcs1.pem 4096
# openssl pkcs8 -topk8 -in private_key_rsa_4096_pkcs1.pem -inform pem -out private_key_rsa_4096_pkcs8-exported.pem -outform pem -nocrypt
#add \n to the certificate: awk 'NF {sub(/\r/, ""); printf "%s\\n",$0;}'  private_key_rsa_4096_pkcs8-exported.pem
gcpAttachments: # gcp storage configuration
  domain: domain.com
  email: dummy@dummy.com
  maxSizeInBytes: 1000000
  pathPrefix: /
  rsaSigningKey: "-----BEGIN PRIVATE KEY-----\nMIIJQwIBADANBgkqhkiG9w0BAQEFAASCCS0wggkpAgEAAoICAQDsoUXEMsxmuPMw\nxfiBI/en/yTcFmThB5WAZknp3sgAJpkuJ9knY96XMh++DbiYeKHgMoZUhAwhRiwy\nMz1geurWRK0EI5Oa5JxlOnzTvoBBpbHf62jICLyUijCR+5A3kgMLyIjk/hJtJaPV\ntHGM0EsybGQwkuv5F6N7v9zA1xOboWzNEEq0uoti8MqklmylXn3BUGanmetW4VEw\njbA4iSnLXXGaeX/Uyh4Ab2OSyRq/SEdPFSqdoB9Dw3OqcYmz/q6o5iOA0Iw9kxqo\ne41xKc/jTpmtrQhULJieNeQLln4bh+VCkWRzHzxvZRFstzpVEggaCvbiOdi65wTQ\ngT6V9JIPWC7xUf3xhmKOplPrjOFqgpfLw9n1RTJSBRd1VCqqYZkU2tNaVw6Qza8P\nvbQpyOJWh+ZJS+Cj6jBaRyHAWdhkC7G2qMrVIKCvoe9s2gkGXsDmJR00RGkwtR3L\nvu0HXWLWvz4yRtA4wl7s1+a0keDnXAMQIroPRFnpfS0jiI3Rs2BDvBou369pgqZ4\nPojyUYT4GGnnYhsiFUcvm1eziOSzg6dmDOZUTIYyLPdy9Z+LpWF2ssHAba5DdDan\n2JzXW8Xx7KRNtnsqP/2GnWtM3bkqpfr+WwDGazGYf/wHIIBG/38/eHCe4AHFJ2XX\n7TG4nuok/r3I+HgAoX4kq0hA7IBWKwIDAQABAoICAQDFrbCXyAwj4GwhGbGRSNfS\nu34ycm7R4sENI+apfpg8MAKVoWpy0qaYTqJf5hyJG3W30t2Pa0Sq43F2eoHSwLzA\nRVz4cTQVGNhiZKr1RVbmAKMJOiMtwMaxnIQY4DxJgCwVQvDBxFLmZaRpmjWl+jhn\npk9ImOSTEiFb9xtW6hYSVJeM9AhE1PYusJPJTXTz7W1G+oDXkOkeilqGIkfN4yBM\nKQMHlmqo/DR2DpfzfxdeJuaTdU5FogecV4KgJ/tup9uHc8LDEPWnVuXVTGoL2G84\nKGiPw1aK4zqYKNMarx0oqK1ooAd3eOfG83rMBIGxob+s6e33bXXWJbpK6T28jjUZ\nCzBN4afueF9MdcpZLMI94irC8axY342BQBjS7cscBtIRuPIIv94aFUy75X8fDy1g\nee1Iq9ft2aXUE237+IBqDngQ8X5qQU859ImAqn1aUjVEcHewJHzDPJ6N/2yueE2/\npya1qj0EhQUusNJDTbapHw6mYaK/aldmo+/nUUrM9Lx8CPNEC3WJTcFhe5Qdq2ix\n04D1qVO1yM1s2uGuCCQbIIQBKoJeJqJBrXVHJqeWrxU/a2VFZc1DQ///M0ZhsB0G\nLRGq8D9NX9rWPlBXYW4SD/040L0bPQKVlCG82MYxijYpPeh7V4N9pJ0DrzDOXkdA\n/vrHv339HSFPdsuXy2gbqQKCAQEA+78INj7FvLdwPwFypSdwNHadXf9u6qVkbnBc\nTzanlW1qpTm6NtxhDylDVx1rTWlzoDE7mwnjSNljyjpJlSLak8uuOf+g4dyTMVy5\n8+XqHrAmMtkcA8DZy3cJ3FmziMkWvMaqhmBommmJ3wecFBeaD9YY8ntUXFOjQmES\nvtMtr8IZFWv7xEL6m3St5LDuQ/mIXCAZFEMUMDVUTaZQzXD7xsk4mD77DEImpY5A\n6NxNkUP2NoiLqq9cIsTUSOUy3YhK1JyXZJBFQON/4J2syS9epAR6QUacaRX2jiK1\nr71LMzkc7Tx6vd1lXqfDcXl09DWriJAIilksfDnBwQh8Wb2wbQKCAQEA8KDaTM/L\nENAnDbbjFt8YurD4Bk9V0FbEqsEGf/1SSuaOtKxOnI1IRaR9coWIwnpoWnpas7Y0\nfvbPKszOCqA2XBcrfW13wcNtW2YD3w2Xwtjf5w/d7yJMFhP0gGlWqNG63KkjOaC5\nV58IolD+tWkr1DK8/bZPmVu4tmM3jzzlSERhn5mKpntNuyPI+MUH1B0fNNyV9oeI\n92OOKMidqcpiTUD/yxNZYJVnaoTSjMaL+JMZGTLzY0gt1q7Hwhjn4mPo0VJ3LC1n\n9Ahpa92YSpDls409SM8d6ULYs15FtzQjdioN23nTHne2Mt0BQn+qMJr5v4Qul7yt\n1eMobum7xydx9wKCAQABGzXOBziXO7cij78ROrsjf+HxJ840+cUXNycwsezKm1B8\nqWRIGW/TwTqqh1aRYIVBjvXUGJcHGu11Vgw8u4p6W8rINndehrme3elzSO9ecye3\n0XxuB8rtOfixHzPKxhdzfOwC6ymKhCw27rGg5PmoWCiD6EbWoQd2ozaR4BuzSgcS\nMQdKNYEkbb7V4nEpm08eGIYDsMfF7nYQYUq5nGV+2iOFh8FSrHe/AoEGhPFSUhoi\n4za56UteW78TEu7GSnMJvCZuKrQjNNy6//Zia/LehaaD4uuNCquqtDxYKVzLPNUD\nteBUNUTcxZ/2P7Jj4FiAoSFoejvXz+kqD/975XmBAoIBADJEuDYRts9VXMM9sKUn\niCgALmBLFJdIeR9e4be9OQLStX9C+80yqqV53ocdJFvUbJZyNx6R8tePQeokDOsl\nWxXT9U7nnnwJEoBkiGyBj3GyEtxXcTqyxIhcNNjaqLLt1Yahgu1YCUAnxgr6tqs5\nRGG5E8hA3NIh2i2n/oRa6V82gdpwngl3et6cdDCcIK2MQ+esKVvuJovf7WPRvTYq\nRGz1JjrLWQGXVJppEv87vyP3vueHwFa+Tm0p6CtBPrgJvSp1etXsymmtlDBng5gY\nOxRObj4Wnp4LS+/0wsWqC7p0wJ5YDeWwhoyLpOa6ethal9ANkho63WnwYZMCGytY\nrzMCggEBAJkGF0m5UFsAQIMwuSJUHnh38h0ZDDq5M/JvonFubCOgt4W5xNHZV3rE\nZitFceTBvfM3VG5GpJY3yBRD6rSWEOBtljhHsVjn77QYzJMBoXDowIeT1ubC8gVg\ntaJ7J9v0xc60kG11+xWsAVbI2BzfgcmTPv7v9Hgme07M2CU6pEe4wFiGrG1gJ0VW\nR8UHZUM/9I9S/LWxerBYOVM8H+RSQ7r8WNzxZuZh30VX3Cx7fzyAQoVZOkK99TXy\nHUveJRssa8sxvlqaiDEXau5Y9MGW+TUpAyjCpSn2L1Ws2RU+i8tiJ2mA8aEB5DP4\ne/Nnz522vAEo/NRpbNfrnLDFmjFnZ+U=\n-----END PRIVATE KEY-----\n"

pubsub: # redis server for pubsub cache
  url: redis://172.16.4.196:6379/cache # change to your redis server
  replicaUrls:
    - redis://172.16.4.196:6379/cacheReplica # change to your redis server

remoteConfig: # remote configuration token
  authorizedTokens:
    - dummy

zkConfig: # zkgroup config, run using your build jar
  serverSecret: AOpPxKOO5ZfrwM3jxBiAj3/PbChC3psSw6mbfXX8/zkJwSy3Ocy0erRJYn2MXiDuQV1g5iz7t/IWgA1t358IvAPIXpmYiP0pbPUrU/uKsO4ZEpjSHB7Zabtra4xbB3XjUFuhxOMqOxof5UrtkV7tgeTnetCOJmbxjd8G7MOny+0PgdqsW+ZdiWYwrCGY8i+Wr1Tx+Kbr+yjmgeVC5FFkrgjgIg58uAXF3i1iQlkPqoVQs2ahJOs9Gdtf1Iz9RxBgBTGzfDAMOe85PGwJZZnRHQ+Dh6az45gDDPCFGNsqyrwCCnNeLxvVMEjRlxDbhHZT3/0lBJUErB8B0MbKz+qgpQqASGjsPT9q+2EpUKGromyHhnjpJGD3Q6vK18IA19EOCurBeHz6TQBS8MCZS8yYaJMUHJj2flAtJBMTZEkGD4llUGv3IPMsBmqbev6DJuc69p+70MsLYI1s6JHVCXHOy3vdGVdR0c83nM6JJQK5nJyRd/FdIdSfVyUiGFVcqnJDCmFMs2ThOb3jcAaZJ166WQVI5lMXjx45FLuP36XO7+oDKlcEc640YgsoPbLLd6lHIFSrVwkbqFbQok9N1o72EBWr/r3heYL5msFTohED0oCrUqBz1uLkLHrHi9zCkntuAzjp6ipAcYtBP0U+AqmPQS65CTvVhYOfn0uU2Jgywm0MAxGqha5Jn6CUO9W4Q6WZmxZakaJsSsNbiDAbC6ffzgj3fXapHjDefi0LYy1bMYzBZm50Y+4MmiHvpFctkFgHDrdnvCXgldcSQ1yGwczWpofPZuPdkj4P/ilrywu5aYcBXc9gRLf2Zq3aeOaIbZCWyMMgaX2qWH+I9LMPaSfusAQaf1YzhJenbL10CnZar9yzEBnTt2q5+aTz17M0qIsRMCRKCrXQNf7mIRLmxevoi6AU746sqaAS0UOVJQVK5oBnUwaOoYzP8qV5JkYM6rIShKIivjHzIKT0LWhYX5wdjQUGf2PFMIBK13zH1wKpoWnmG0zwtcCDSs0inW9W3MR0Eg
  serverPublic: AOrBeHz6TQBS8MCZS8yYaJMUHJj2flAtJBMTZEkGD4llUGv3IPMsBmqbev6DJuc69p+70MsLYI1s6JHVCXHOy3saf1YzhJenbL10CnZar9yzEBnTt2q5+aTz17M0qIsRMCRKCrXQNf7mIRLmxevoi6AU746sqaAS0UOVJQVK5oBnBn9jxTCAStd8x9cCqaFp5htM8LXAg0rNIp1vVtzEdBI
  enabled: true

accountsDatabase: # database for account
  driverClass: org.postgresql.Driver
  user: signal
  password: tl*signal
  url: "jdbc:postgresql://172.16.4.196:5432/accountdb"
  properties:
    charSet: UTF-8

messageStore: # database for message
  driverClass: org.postgresql.Driver
  user: signal
  password: tl*signal
  url: "jdbc:postgresql://172.16.4.196:5432/messagedb"
  properties:
    charSet: UTF-8

abuseDatabase: # database for abuse
  driverClass: org.postgresql.Driver
  user: signal
  password: tl*signal
  url: "jdbc:postgresql://172.16.4.196:5432/abusedb"
  properties:
    charSet: UTF-8

gcm: # firebase messaging
  senderId: 569472023376 # your sender id
  apiKey: AAAAhJcte1A:APA91bGczChxovomKuBiCGFAJPJEGc2_cTX6jvxOTZL0eWSYiqZqklkxKljpQpXcq8fm30A_QJnijJ9smHZyYpHJ6FqE6AypKUEnMJm5BDTkfHw_BtOAb513Uo7e5VhkSzwvOIOuClGu # your api key

recaptcha: # google recaptcha v3
  secret: 6LcJ9tgZAAAAAB3pwoN_SM45MDZEjzycPhNI-z-8 # your recaptcha secret

accountDatabaseCrawler: # crawler for account database
  chunkSize:       1000
  chunkIntervalMs: 1000000

apn:
  pushCertificate: "-----BEGIN CERTIFICATE-----\r\nMIIFjzCCBHegAwIBAgIRfkSIVVtC9UIwDQYJKoZIhvcNAQEFBQAwgZYxCzAJBgNV\r\nBAYTAlVTMRMwEQYDVQQKDApBcHBsZSBJbmMuMSwwKgYDVQQLDCNBcHBsZSBXb3Js\r\nZHdpZGUgRGV2ZWxvcGVyIFJlbGF0aW9uczFEMEIGA1UEAww7QXBwbGUgV29ybGR3\r\naWRlIERldmVsb3BlciBSZWxhdGlvbnMgQ2VydGlmaWNhdGlvbiBBdXRob3JpdHkw\r\nHhcNMTkwNTA5MTc0NzUyWhcNMjAwNTA4MTc0NzUyWjCBjjElMCMGCgmSJomT8ixk\r\nAQEMFWNvbS5xYW5kb3JhcHAucWFuZG9yMzFDMEEGA1UEAww6QXBwbGUgRGV2ZWxv\r\ncG1lbnQgSU9TIFB1c2ggU2VydmljZXM6IGNvbS5xYW5kb3JhcHAucWFuZG9yMzET\r\nMBEGA1UECwwKTlA2UE5GUUdBODELMAkGA1UEBhMCVVMwggEiMA0GCSqGSIb3DQEB\r\nAQUAA4IBDwAwggEKAoIBAQDIo+8GD6chbxCFDI7bTK6iTxQHnD/FiXJvEYBbO3ey\r\nQV8/XZm66VbO+RbA4UArA2bjdW5KZkSQ7hSYJcomQCmcmpqmrXjcaL0KfeWinSz4\r\nmbXxoXK9JsoUSjOfy7yXHGDLZSHGVvn5gO1FU9WPX3Iu7YYMT1hwnMgmZIuzn5K9\r\nAiyxvQzSlIlEsnpoqTDUz+1eXtPXAISPQT8+jM8JoZohTrODuUUj2rSPWi62kMBP\r\nsX4H4ncSjI56DG/E0lvUV7d0PEiUnoxGwzycmGJVgpZqv/E6p1eUNT7Utl4ktuiq\r\nEv8ft3+brJx+FokMi7AKjxLvlYS18LTG6JbQMcmXHsdlAgMBAAGjggHlMIIB4TAJ\r\nBgNVHRMEAjAAMB8GA1UdIwQYMBaAFIgnFwmpthhgi+zruvZHWcVSVKO3MIIBDwYD\r\nVR0gBIIBBjCCAQIwgf8GCSqGSIb3Y2QFATCB8TCBwwYIKwYBBQUHAgIwgbYMgbNS\r\nZWxpYW5jZSBvbiB0aGlzIGNlcnRpZmljYXRlIGJ5IGFueSBwYXJ0eSBhc3N1bWVz\r\nIGFjY2VwdGFuY2Ugb2YgdGhlIHRoZW4gYXBwbGljYWJsZSBzdGFuZGFyZCB0ZXJt\r\ncyBhbmQgY29uZGl0aW9ucyBvZiB1c2UsIGNlcnRpZmljYXRlIHBvbGljeSBhbmQg\r\nY2VydGlmaWNhdGlvbiBwcmFjdGljZSBzdGF0ZW1lbnRzLjApBggrBgEFBQcCARYd\r\naHR0cDovL3d3dy5hcHBsZS5jb20vYXBwbGVjYS8wEwYDVR0lBAwwCgYIKwYBBQUH\r\nAwIwTQYDVR0fBEYwRDBCoECgPoY8aHR0cDovL2RldmVsb3Blci5hcHBsZS5jb20v\r\nY2VydGlmaWNhdGlvbmF1dGhvcml0eS93d2RyY2EuY3JsMB0GA1UdDgQWBBR6BPca\r\ngaRwijNzbL4lcYrJkU2r7TALBgNVHQ8EBAMCB4AwEAYKKoZIhvdjZAYDAQQCBQAw\r\nDQYJKoZIhvcNAQEFBQADggEBAFcIWIc1T0PtgeaMgjwQcTmfJGy8MUdIO/hdElo/\r\nOZF4ts4c2xkddanZ9IzOCj/HzmRJEs6WVZhNxySc3Cxo6KejsLbGLJmMoEh72xyQ\r\nwgnMBiapMnRhCfd68NMnTUClNHvGsg+NipnAN63r+HZSgPsCMXHsEMyZ+qQendRc\r\nDZH6m5FN1TqdAVtChdDPItzYJuQpyeKJpiiQGeCd6YjCELkWVxHcTU67CWmkuVqx\r\n9BRoANbJXty3b9T5KHxJYcEMj3pvsgcTOR/nGKIT9+B2iqrt6i/YY2n4p5NXXFzZ\r\nHewPc93srGXfyrvW7SeQs+93vZ7WlntfihY7WCoUbEOnHso=\r\n-----END CERTIFICATE-----"
  pushKey: "-----BEGIN RSA PRIVATE KEY-----\r\nMIIEpQIBAAKCAQEAyKPvBg+nIW8QhQyO20yuok8UB5w/xYlybxGAWzt3skFfP12Z\r\nuulWzvkWwOFAKwNm43VuSmZEkO4UmCXKJkApnJqapq143Gi9Cn3lop0s+Jm18aFy\r\nvSbKFEozn8u8lxxgy2Uhxlb5+YDtRVPVj19yLu2GDE9YcJzIJmSLs5+SvQIssb0M\r\n0pSJRLJ6aKkw1M/tXl7T1wCEj0E/PozPCaGaIU6zg7lFI9q0j1outpDAT7F+B+J3\r\nEoyOegxvxNJb1Fe3dDxIlJ6MRsM8nJhiVYKWar/xOqdXlDU+1LZeJLboqhL/H7d/\r\nm6ycfhaJDIuwCo8S75WEtfC0xuiW0DHJlx7HZQIDAQABAoIBAFNo+1xMs5FNp9N4\r\nBgebGFp3f38ucMCBRGZyIydKUJd1X9Bq7BbtHF6M5O2odtGq52IWFpStcUHDCCK8\r\nSw6dy+7DwxkZss4GaNhswENbDjAHTsE1+goyjv3iXxXGUA+OB5tm3qSi0ebstzcE\r\nBBtHdaOWsQx7C+w88WQslntFEm6qNSqeM1s5eQ20wSnlAA43Pm+NdVNM+JYX4iqt\r\n/MFdaPINE5XAXyBRAYir0l1dkofeGsb4rCuZmXSmjRRcC9vdhzmjrDUxLspOI7du\r\nUT7vYy3/hWFdng5oHu7JoDVrxF8/5e11j04jTq8SiHYfxUdR/Pmzt4/Nnu8SVjDJ\r\nesZJhwECgYEA7ElQyw2fzF3CQ2x526SBvLfFSxuX8zDkPjFtsrpZf78MHz9AR3ak\r\nlgEjR9aOfeWC1nRRZ6kGG8AgbpIZEN5KoCwZM98D6oub0VIg8iuR1UeArjebI8QV\r\nq2q5BeR3v2nmHsDXeG57D7O7DRko1tazp+d3/19hmMBOa4os19SsEaUCgYEA2WFH\r\nPtVwRtsQNcuKBCKHGzEVDG6Gm86kye2AdfJB7USr0fvD3HRah/chGi+foz+CDwwA\r\nzuBcgL45rSZZCTA9AFzihVpAFJ+a3GDgT/hSjJmMX3vHmySaZABmKNsiXRlPW+Fr\r\n7jkXwk7JH6emgcBH9d+Gyyp6ybVZvv/tNrFCcsECgYEA1DhtNlLASZ+UUVZmhF3W\r\noJc1vmXELgqllS5z5mj05YXD73Sx2P24iXnwJB+Sz4SJ5O+IBeCLufTvrB/QH5Rn\r\n1kCFSk9thwVpJ7HqIVf8nWChNNiAoLkG9XTfRWmUG/mTU9/EJ0ijgtDcmcEVKxCf\r\nP5jn8BfM4pMmW/Q4nolHGnkCgYEAnnLT1a8KSft/k1arYVwxktZx+z/NCmDTqQRf\r\nMJnHCEWX4FVdbKG7I4Q1Mrsn53xxNrqPFDxh8M23iMh8+b+Zl1wdGQqxztaPsLdE\r\nicX9ldKOiULWOfWyO9Y2oO0p3SaHu/dSDrC66r02yMYRDl6zlTq7K/fozIJNynUN\r\n2WHXh4ECgYEAneclaDj/KMtedyaJcblyEjtpzW3V/Gotws2cAaHqVaWDJHRrp0bl\r\nZNg8Jjf/NoixxENZ5bdduAR3JEjTwScRpOluO45Huq2gIMS7jsBKoDAvF94DNUI5\r\nNDtK8x/8+SOdk5HAGNHDoMqVbgZ2NpeOIGxzoZUCCK4f1j1CZbeEIio=\r\n-----END RSA PRIVATE KEY-----"
  bundleId: com.notused
  sandbox: true

unidentifiedDelivery:
  certificate: CiYI5A8SIQW9rmfUa+JPQSy0z+VOB11kQ+EZrn7UTJN35BGiDCBddBJABMcEDSyqIkB9AMrQymKejrA9bgqnIhmEujFYH71SCzF45BekHf0bW+A07hJt1fBXmHX8bPLzc1tN4kfn832iDw== # Your generated certificate
  privateKey: uFA2mynj1mDsDRO/9QV0Fv4COMGd2aqg+pvn5JYF5mE= # Change this to you generated private key
  expiresDays: 365

voiceVerification: # voice otp verification, afaik it use vox service
  url: https://server.chatapp.net
  locales:
    - en

pushScheduler: # redis server for push scheduler
  url: redis://172.16.4.196:6379/pushScheduler # change to your redis server
  replicaUrls:
    - redis://172.16.4.196:6379/pushSchedulerReplica # change to your redis server

server: # server configuration
  applicationConnectors:
    - type: http
      port: 8080 # your signal server will run on this port
  adminConnectors:
    - type: http
      port: 8081 # your signal server admin will run on this port
